// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hehehhehehehehehe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hehehhehehehehehe));
        
        string IMigrationMetadata.Id
        {
            get { return "202112161700302_hehehhehehehehehe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
